# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField()),
                ('discount_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('restraunt_name', models.CharField(max_length=100)),
                ('restraunt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Special_discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField()),
                ('date', models.DateField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.Restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.Restaurants')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='discounts',
            name='restarant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restro.Restaurants'),
        ),
    ]
