# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0002_restaurants_restraunt_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='pin',
            field=models.IntegerField(default=1234),
        ),
    ]
