# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restro', '0003_restaurants_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='visits',
            name='last_visit',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
